version: '3.8'

services:
    redis:
        image: redis:alpine
        container_name: oauth-redis
        ports:
            - "6379:6379"

    postgres:
        image: postgres:latest
        container_name: oauth-postgres
        environment:
            POSTGRES_USER: hero
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    php-fpm:
        build: ./
        container_name: oauth-php-fpm
        working_dir: /application
        volumes:
            - .:/application

    webserver:
        image: nginx:alpine
        container_name: oauth-webserver
        working_dir: /application
        volumes:
            - .:/application
            - .:/etc/nginx/conf.d
            - ./nginx:/var/log/nginx
        ports:
            - "80:80"

